[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.module]
source = 'nativefs.lua'
before = 'main.lua'
name = 'nativefs'

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self:load_profile(G.SETTINGS.profile or 1)"
position = "after"
payload = "initChallenges()"
match_indent = true
overwrite = false

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = [
    "mod.lua"
]

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "function init_localization()"
position = "after"
payload = '''
G.localization.misc.challenge_names.c_mod_riffraff_1= "Riff-Raffle"
G.localization.misc.challenge_names.c_mod_face_down_1= "Face Down"
'''
match_indent = true
overwrite = false

# sacreligeous implimentation -- "quick and dirty" for sure
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.facing = 'front'"
position = "at"
payload = "if G.GAME.modifiers.face_down == true then self.facing = 'back' else self.facing = 'front' end"
match_indent = true
overwrite = true

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.sprite_facing = 'front'"
position = "at"
payload = "if G.GAME.modifiers.face_down == true then self.sprite_facing = 'back' else self.sprite_facing = 'front' end"
match_indent = true
overwrite = true

# let's not mention this ever again.
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = "local stay_flipped = G.GAME and G.GAME.blind and G.GAME.blind:stay_flipped(self, card)"
position = "before"
payload = """
card.facing = 'front'
card.sprite_facing = 'front'
"""
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "elseif v.id == 'no_shop_jokers' then"
position = "before"
payload = """
 G.debug_tooltip_toggle = false
elseif v.id == 'face_down' then
    self.GAME.modifiers.face_down = true
    G.debug_tooltip_toggle = true
"""
match_indent = true
overwrite = false