[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.module]
source = 'nativefs.lua'
before = 'main.lua'
name = 'nativefs'

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "self:load_profile(G.SETTINGS.profile or 1)"
position = "after"
payload = "initChallenges()"
match_indent = true
overwrite = false

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = [
    "mod.lua"
]

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "function init_localization()"
position = "after"
payload = '''
G.localization.misc.challenge_names.c_mod_riffraff_1 = "Riff-Raffle"
G.localization.misc.challenge_names.c_mod_fleeting_1 = "Anapodaphobia"
G.localization.misc.challenge_names.c_mod_tarot_tycoon_1 = "Tarot Tycoon"
G.localization.misc.challenge_names.c_mod_unfortunate_1 = "Unfortunate"
G.localization.misc.challenge_names.c_mod_jimbofull_1 = "Jumbofull"
'''
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "function init_localization()"
position = "after"
payload = '''
G.localization.misc.v_text.ch_c_no_shop_planets = {"Planets no longer appear in the {C:attention}shop"}
G.localization.misc.v_text.ch_c_no_shop_tarots = {"Tarot cards no longer appear in the {C:attention}shop"}
G.localization.misc.v_text.ch_c_all_perishable = {"All Jokers are {C:perishable}Perishable{}"}
G.localization.misc.v_text.ch_c_credit = {"Concept by: {C:green}#1#{}"}
'''
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if (area == G.shop_jokers) or (area == G.pack_cards) then"
position = "before"
payload = '''
if G.GAME.modifiers.all_perishable then
     card:set_perishable(true)
end
'''
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "elseif v.id == 'no_shop_jokers' then"
position = "before"
payload = """
elseif v.id == 'all_perishable' then
    self.GAME.modifiers.all_perishable = true
elseif v.id == 'no_shop_planets' then
    self.GAME.planet_rate = 0
elseif v.id == 'no_shop_tarots' then
    self.GAME.tarot_rate = 0
"""
match_indent = true
overwrite = false
